services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    network_mode: host
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 2s

