services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    network_mode: host
    environment:
      - PORT=3000
      - ZETADB_URL=${ZETADB_URL}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_WEBHOOK_SECRET_PATH=${STRIPE_WEBHOOK_SECRET_PATH}
    env_file:
      - .env
