export const StatusCodes = {
  OK: 'OK',
  INVALID_JSON: 'INVALID_JSON',
  INVALID_PRODUCT_ID: 'INVALID_PRODUCT_ID',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  INVALID_ORDER_INPUT: 'INVALID_ORDER_INPUT',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  ORDER_CREATION_FAILED: 'ORDER_CREATION_FAILED',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST: "BAD_REQUEST",
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT'
} as const;

export type StatusCode = typeof StatusCodes[keyof typeof StatusCodes];
